# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main, automation2 ]
  pull_request:
    branches: [ main, automation2 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Upload All-in-One Jar
        uses: actions/upload-artifact@v3
        with:
          name: WNT
          path: build/libs/*.jar

      - name: Upload Separate Jars
        uses: actions/upload-artifact@v3
        with:
          name: WNT Subprojects
          path: |
            0EX/build/libs/*.jar
            Blackbox/build/libs/*.jar
            Dumper/build/libs/*.jar
            Supervisor/build/libs/*.jar
            Toolbox/build/libs/*.jar
